import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const apiBaseUrl = "http://jsonplaceholder.typicode.com/users";
console.log("link:", Link);
console.log("image:", Image);
export const getStaticProps = async () => {
  const res = await fetch(apiBaseUrl);
  const data = await res.json();
  console.log(data);
  return {
    props: { users: data },
  };
};

export default function Home({ users }) {
  const [input, setInput] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          {" "}
          <strong>API key:</strong> {apiBaseUrl}
        </p>

        <input
          value={input}
          onInput={(e) => setInput(e.target.value)}
          type="text"
          placeholder="test api address here..."
          id="apiBaseUrl"
          className={styles.description}
        />
        {users.map((user) => (
          <div key={user.id}>
            {JSON.stringify(user, null, 4)} <hr />
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
